[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.autojump]
github = "wting/autojump"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.blackbox]
github = "StackExchange/blackbox"

[plugins.git-secret]
github = "sobolevn/git-secret"

[plugins.kube-ps1]
github = "jonmosco/kube-ps1"

[plugins."z.lua"]
github = "skywind3000/z.lua"

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.ansiweather]
github = "fcambus/ansiweather"

[plugins.base16-shell]
github = "chriskempson/base16-shell"

[plugins.k]
github = "supercrabtree/k"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"

[plugins.zsh-nvm]
github = "lukechilds/zsh-nvm"

[plugins.forgit]
github = "wfxr/forgit"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-histdb]
github = "larkery/zsh-histdb"

[plugins.sysadmin-util]
github = "skx/sysadmin-util"

[plugins.zsh-iterm-touchbar]
github = "iam4x/zsh-iterm-touchbar"

[plugins.git-extra-commands]
github = "unixorn/git-extra-commands"

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.wd]
github = "mfaerevaag/wd"

[plugins.zaw]
github = "zsh-users/zaw"

[plugins.zsh-autoenv]
github = "Tarrasch/zsh-autoenv"

[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.alias-tips]
github = "djui/alias-tips"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins."auto-fu.zsh"]
github = "hchbaw/auto-fu.zsh"

[plugins.zsh-notify]
github = "marzocchi/zsh-notify"

[plugins.zsh-z]
github = "agkozak/zsh-z"
